### ISSUE TITLE
Gerarchia voci di menù

### ISSUE THREAD

**Issue by atodaro** [eshiol/j2xml#3]
### Steps to reproduce the issue
Genero un file di esportazione di un menù già strutturato con voci di menù principali e altre voci di gerarchia inferiore e importo in altro sito il menù tramite l'xml

### Expected result
Nel sito di importazione, le diverse voci di menù rispettano l'ordine gerarchico del sito di provenienza

### Actual result
Tutte le voci di menù sono importate come voci principali di menù

### System information (as much as possible)
Joomla 3.8.2 su sito di esportazione e sito di importazione
J2xml su entrambi i siti come da immagine
![screen git 2](https://user-images.githubusercontent.com/12257435/33255557-879f0442-d34e-11e7-949a-ea54611e623e.png)

**Comment by kokbira** [comment]
Same for me :(
