### ISSUE TITLE
JUserHelper Issue

### ISSUE THREAD

**Issue by okanime** [eshiol/j2xml#7]
I am getting this error when trying to import users and content.

An error has occurred.
0 Class 'eshiol\J2XML\Table\JUserHelper' not found	
/var/www/html/testbed/libraries/eshiol/j2xml/Table/User.php:193

`

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/eshiol/j2xml/Table/User.php:193
2 | eshiol\J2XML\Table\User::import() | JROOT/libraries/eshiol/j2xml/Importer.php:134
3 | eshiol\J2XML\Importer->import() | JROOT/administrator/components/com_j2xml/controllers/cpanel.php:220
4 | J2xmlControllerCpanel->import() | JROOT/libraries/src/MVC/Controller/BaseController.php:710
5 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_j2xml/j2xml.php:137
6 | require_once() | JROOT/libraries/src/Component/ComponentHelper.php:402
7 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT/libraries/src/Component/ComponentHelper.php:377
8 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:101
9 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:159
10 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:196
11 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/index.php:51

`

Kindly advise on a workaround or a fix for this.

Thanks.

**Comment by tonypartridge** [comment]
Is this still an issue?
