### ISSUE TITLE
Error when importing Wordpress XML

### ISSUE THREAD

**Issue by rodolphopedra** [eshiol/j2xml#8]
When importing a Wordpress XML, ocuurs this error:

Class 'J2XMLVersion' not found

**Comment by windwebpl** [comment]
J2XML Wordpress Importer 4.4.23 is not compatible with J2XML 3.7, please use 
https://www.eshiol.it/files/plg_j2xml_wordpress/plg_j2xml_wordpress-4.4.31.zip
